source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'
target 'MyMediaPlayer' do
  pod 'MTDNavigationView', '~> 0.2.4'
# pod 'MTDNavigationView', :git => 'https://github.com/WessonWu/MTDNavigationController.git'
  pod 'MLeaksFinder'
end
