source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'
target 'MyMediaPlayer' do
#  pod 'MTDNavigationView', '~> 0.1.1'
pod 'MTDNavigationView', :git => 'https://github.com/WessonWu/MTDNavigationController.git'
end
