# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CycleScrollView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CycleScrollView
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.5.0'
end
