source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitlab.4399doc.com/CocoaPods/CocoaPodsRepos.git'
use_frameworks!

platform :ios, '9.3'

target 'Thor_Example' do
  pod 'Thor', :subspecs => ['Core', 'APIExtension', 'RxThor'], :path => '../'
  
  pod 'RxCocoa', '~> 5.0'
  pod 'RxSwift', '~> 5.0'
  pod 'HandyJSON'

  target 'Thor_Tests' do
    inherit! :search_paths

    
  end
end
