use_frameworks!

platform :ios, '9.3'

target 'Thor_Example' do
  pod 'Thor', :subspecs => ['Core', 'RxThor'], :path => '../'
  
  pod 'RxCocoa', '~> 4.0'
  pod 'RxSwift', '~> 4.0'
  pod 'HandyJSON'

  target 'Thor_Tests' do
    inherit! :search_paths

    
  end
end
