# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # desc "Push a new beta build to TestFlight"
  # lane :beta do
  #   build_app(scheme: "TestAppStore")
  #   upload_to_testflight
  # end

  desc "Read Env"
  lane :read_env do
    name = ENV['WESSON_NAME']
    abc = ENV["WESSON_ABC"]
    UI.message "#{name}, #{abc}"
  end

  lane :test_cert do
    cert
  end

  lane :test_sigh do
    sigh
  end

  lane :test do
    run_tests(scheme: "TestAppStoreTests", devices: ["iPhone 11 Pro Max"])
  end

  error do |lane, exception, options|
    subject = "Execute #{lane} lane failed."
    body = "Error: #{exception}, Options: #{options}"
    mail :subject => subject,
         :body => body
  end

  lane :mail do |options|
    mail_to :subject => options[:subject], 
            :body => options[:body]
  end

end
