# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'
inhibit_all_warnings!

target 'LocalOrRemoteNotification' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocalOrRemoteNotification
  pod 'CocoaDebug', :configurations => ['Debug']
end
